### ISSUE TITLE
Not enough values to unpack when opening a specific pdf

### ISSUE THREAD

**Issue by HowcanoeWang** [pdfarranger/pdfarranger#692] opened 2022-07-28 05:04 UTC
Describe the bug
----------------

Unable to save / save as / export the specific pdf. But another pdf seems no problem.

To Reproduce
------------

1.  Open the PDF arranger
2.  Drag the pdf into the GUI, or click the import button on the top left (neither works)
3.  Click the "Save", or "Save As", or "Export"
4.  See the error

Input files
-----------

The pdf can be achieved here: https://drive.google.com/file/d/1r_U6dMKPR3yWx9oeoYEl3NGLsQ1JX2jz/view?usp=sharing

Screenshots
-----------

![image](https://user-images.githubusercontent.com/19968935/181423532-03363e85-ec66-402a-aa05-74319e7a4631.png)

System and Versions
-------------------

-   PDF Arranger version 1.8.1, and download from github page releases
-   seems not install pikepdf by \*.msi installer.
-   Windows 11

**Comment by dreua** [comment] 2022-07-28 11:52
Thanks for the report, I can reproduce this:

## Fedora 36, RPM

```
[dar@cdf ~]$ pdfarranger 
/usr/lib64/python3.10/site-packages/pikepdf/models/metadata.py:377: UserWarning: The metadata field /robots with value 'pikepdf.String("noindex")' has no XMP equivalent, so it was discarded
  warn(msg)

/usr/lib64/python3.10/site-packages/pikepdf/models/metadata.py:377: UserWarning: The metadata field /CrossMarkDomains[2] with value 'pikepdf.String("sciencedirect.com")' has no XMP equivalent, so it was discarded
  warn(msg)

/usr/lib64/python3.10/site-packages/pikepdf/models/metadata.py:377: UserWarning: The metadata field /CrossmarkMajorVersionDate with value 'pikepdf.String("2010-04-23")' has no XMP equivalent, so it was discarded
  warn(msg)

/usr/lib64/python3.10/site-packages/pikepdf/models/metadata.py:377: UserWarning: The metadata field /CrossmarkDomainExclusive with value 'pikepdf.String("true")' has no XMP equivalent, so it was discarded
  warn(msg)

/usr/lib64/python3.10/site-packages/pikepdf/models/metadata.py:377: UserWarning: The metadata field /CrossMarkDomains[1] with value 'pikepdf.String("elsevier.com")' has no XMP equivalent, so it was discarded
  warn(msg)

/usr/lib64/python3.10/site-packages/pikepdf/models/metadata.py:377: UserWarning: The metadata field /doi with value 'pikepdf.String("10.1016/j.compag.2020.105760")' has no XMP equivalent, so it was discarded
  warn(msg)

/usr/lib64/python3.10/site-packages/pikepdf/models/metadata.py:377: UserWarning: The metadata field /ElsevierWebPDFSpecifications with value 'pikepdf.String("6.5")' has no XMP equivalent, so it was discarded
  warn(msg)

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pdfarranger/pdfarranger.py", line 976, in choose_export_pdf_name
    self.save(mode, file_out)
  File "/usr/lib/python3.10/site-packages/pdfarranger/pdfarranger.py", line 160, in wrapper
    func(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pdfarranger/pdfarranger.py", line 1044, in save
    m = metadata.merge(self.metadata, self.pdfqueue)
  File "/usr/lib/python3.10/site-packages/pdfarranger/metadata.py", line 85, in merge
    for k, v in meta.items():
  File "/usr/lib64/python3.10/_collections_abc.py", line 906, in __iter__
    yield (key, self._mapping[key])
  File "/usr/lib64/python3.10/site-packages/pikepdf/models/metadata.py", line 284, in wrapper
    return fn(self, *args, **kwargs)
  File "/usr/lib64/python3.10/site-packages/pikepdf/models/metadata.py", line 655, in __getitem__
    return next(self._get_element_values(key))
  File "/usr/lib64/python3.10/site-packages/pikepdf/models/metadata.py", line 646, in _get_element_values
    yield from (v[2] for v in self._get_elements(name))
  File "/usr/lib64/python3.10/site-packages/pikepdf/models/metadata.py", line 646, in <genexpr>
    yield from (v[2] for v in self._get_elements(name))
  File "/usr/lib64/python3.10/site-packages/pikepdf/models/metadata.py", line 628, in _get_elements
    qname = self._qname(name)
  File "/usr/lib64/python3.10/site-packages/pikepdf/models/metadata.py", line 560, in _qname
    prefix, tag = name.split(':', maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)
[dar@cdf ~]$ pdfarranger --version
PDF Arranger-1.8.2
pikepdf-5.1.3
libqpdf-10.6.3
```

In this case I got the same error dialog.

## Flatpak

![image](https://user-images.githubusercontent.com/15114715/181494827-b5a4cc82-27d4-4b60-ac69-d082f1e9e76f.png)

```
[... User Warnings ...]
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/pdfarranger/pdfarranger.py", line 976, in choose_export_pdf_name
    self.save(mode, file_out)
  File "/app/lib/python3.9/site-packages/pdfarranger/pdfarranger.py", line 160, in wrapper
    func(*args, **kwargs)
  File "/app/lib/python3.9/site-packages/pdfarranger/pdfarranger.py", line 1044, in save
    m = metadata.merge(self.metadata, self.pdfqueue)
  File "/app/lib/python3.9/site-packages/pdfarranger/metadata.py", line 85, in merge
    for k, v in meta.items():
  File "/usr/lib/python3.9/_collections_abc.py", line 851, in __iter__
    yield (key, self._mapping[key])
  File "/app/lib/python3.9/site-packages/pikepdf-5.4.0-py3.9-linux-x86_64.egg/pikepdf/models/metadata.py", line 283, in wrapper
    return fn(self, *args, **kwargs)
  File "/app/lib/python3.9/site-packages/pikepdf-5.4.0-py3.9-linux-x86_64.egg/pikepdf/models/metadata.py", line 665, in __getitem__
    raise KeyError(key) from None
KeyError: 'LMfnsn9j-mgz8mM-Gotf9ncNNngqKlt7.yt6GoduQyMj.mM78zt_-o9ePnt6SodmKnd-Tma'
```

**Comment by jeromerobert** [comment] 2022-07-30 16:24
This is a duplicate of #626 so already fixed in master.

**Closed by jeromerobert** 2022-07-30 16:24 UTC
Labels: not our bug, bug
