### ISSUE TITLE
DPI issues when using multiple monitors

### ISSUE THREAD

**Issue by hdijkema** [pdfarranger/pdfarranger#491] opened 2021-05-18 09:36 UTC
Describe the bug
----------------

When I use PDF Arranger in a multi-monitor situation, and try to move a page, the 'pipe' that marks where the page will be moved to is only correctly, i.e. at the right page, displayed on one of the two monitors (probably this is only a porblem when the monitors have different DPIs). In my situation I've got a 96dpi monitor attached to my laptop which has about 150dpi. Moving works correctly on the laptop screen in this case. 

To Reproduce
------------

1.  Make Windows use 2 monitors (extend the desktop). Make sure the two displays have different DPIs.
2.  Try to move a page with the application displayed on each monitor. 
3.  See what happens to the 'pipe' that indicates where the page is moved to. 

Expected behavior
-----------------

Correct positioning of the 'pipe' on every monitor where pdfarranger displays its content. 

Input files
-----------

n.a.

Screenshots
-------------

![pdfarranger_1](https://user-images.githubusercontent.com/745693/118628770-37f65000-b7cd-11eb-9248-5d8c181e1230.jpg)

System and Versions
-------------------

-   1.7.1 portable
-   don't know.
-   Windows 10, multiple monitors.

**Comment by angsch** [comment] 2021-05-18 09:57
This is unfortunately an inherited bug we cannot do anything about.

Duplicate of https://github.com/pdfarranger/pdfarranger/issues/468

**Closed by angsch** 2021-05-18 09:57 UTC
