### ISSUE TITLE
Image format is not supported by img2pdf for jpg

### ISSUE THREAD

**Issue by yw4z** [pdfarranger/pdfarranger#937] opened 2023-08-11 09:49 UTC
![Screenshot-20230811123729](https://github.com/pdfarranger/pdfarranger/assets/28517890/169b84ef-7dfd-45e7-bd40-bd66eb47c191)

Hi,
I got an error if i try to add jpg files created by Keyshot app, its quite popular for rendering 
I convert them to png to solve this, then PDF arranger imports without problem
Using latest version on windows 10

here is example file, also added as zip to prevent any compression by github

![untitled 553](https://github.com/pdfarranger/pdfarranger/assets/28517890/c3187f23-ecc3-45ac-aee3-2a56d051c745)
[untitled.553.zip](https://github.com/pdfarranger/pdfarranger/files/12320308/untitled.553.zip)

Thanks

**Comment by jeromerobert** [comment] 2023-08-12 20:19
I cannot reproduce that bug. I suspect an issue with PIL loading because of an incompatible .dll in PATH. Such problems (#645) are supposed to be fixed by https://github.com/pdfarranger/pdfarranger/commit/fed42f3d7a53756dd363449d09dccc129db7ec7c but may be we are missing something.

Could you try to reproduce that with a clean PATH environment variable. For example:
* start cmd.exe
* `c:\> set PATH=c:\windows;c:\windows\system32`
* `c:\> cd path\to\pdfarranger\`
* `c:\> pdfarranger`

**Comment by jeromerobert** [comment] 2023-08-12 20:40
Are other .jpg and .png files properly imported ?

**Comment by yw4z** [comment] 2023-08-12 20:53
yes i convert that jpg files to png then i can import them, i have tried another jpg file i have same result.

i thought its only happening with keyshot outputs but looks like its all jpgs. i have tried 5+ jpgs from different resources

i dont want to mess with env variables because it can broke other apps,

here is result for PATH on cmd
`C:\Windows\system32\WBEM;
C:\Windows\system32\WBEM;
C:\Windows\system32;
C:\Windows;
C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Program Files\Bandizip\;
C:\Program Files\Common Files\Autodesk Shared\;
C:\Program Files\dotnet\;
C:\Users\xxxx\AppData\Local\Microsoft\WindowsApps;`

also my pdf arranger installed on C:\ProgramData\Apps\Work\PDFarranger as portable

windows version

![Screenshot-20230812234634](https://github.com/pdfarranger/pdfarranger/assets/28517890/5bbe2677-0624-4d2f-b078-9d16986cd02a)

**Comment by yw4z** [comment] 2023-08-12 21:13
i have tried old versions up to 1.8.2 result is same

launched pdf arranger from cmd, same
![Screenshot-20230813000338](https://github.com/pdfarranger/pdfarranger/assets/28517890/a54159a3-1504-4105-a5a5-eb4287638296)

installed using full installer, same

is there a requirement to run pdf arranger, i have no problems with other apps

**Comment by JunglePredator** [comment] 2023-09-13 22:38
Are you able to attach one of the problem JPEGs?

**Comment by JunglePredator** [comment] 2023-09-13 22:51
I'm running PDF Arranger 1.10.0 under Windows 10 via the Windows installer & have no problems with your sample.
I ran it through xnview's file conversion & compared to your sample there's a couple things missing in the JPEG:

Doesn't report:
Exif Byte Order 	 Little-endian (Intel, II)	
DPI


For running PDF Arranger from command line you can temporarily 'set PATH=' & it doesn't change the PATH environment outside that command window.
I suggest you try that.
Also are you able to track down what library your Keyshot uses for JPEG creation?

**Comment by yw4z** [comment] 2023-09-13 23:27
i use pdf arranger to merge renderings to presentation mostly. i thought its only related with keyshot outputs but nope. its happening on all jpg files. 
did i get correct, still cant open jpg files
![Screenshot-20230914021657](https://github.com/pdfarranger/pdfarranger/assets/28517890/75da1ba9-ab78-43e2-a06e-520c999a47b2)
some services disabled on my system is there a requirement about services or other things

**Comment by JunglePredator** [comment] 2023-09-13 23:38
Going by your screenshot you have to 'set PATH=' first not second; otherwise it'll run off the full normal path which is what jeromerobert thinks is causing the problem.
In both your posted screenshots you haven't actually modified anything; PDF Arranger launched the same as if you had launched it from the Start Menu.
jeromerobert suggests setting path to be just the 2 core Windows directories however, since it's temporary, I'd suggest setting path to completely null (which is what 'set PATH=' will do).
In general, if the system is well off, programs will still launch with a null path. (There are a few exceptions to this rule but PDF Arranger, installed in the default location of '%localappdata%\programs' is not one of them.)

**Comment by yw4z** [comment] 2023-09-14 01:18
![Screenshot-20230914035357](https://github.com/pdfarranger/pdfarranger/assets/28517890/7eed86c6-845a-4ab4-819d-df6886601d8e)
still i  get same error
also i have tried full installer before and result was same

i just tried changing file extension to jpeg instead of jpg and it imported without problem. tested with 2 different files

thanks for taking your  time

**Comment by JunglePredator** [comment] 2023-09-14 03:58
Well, it does sound like something the PDF Arranger team may want to look into, because extension shouldn't matter.

Hopefully they don't mind me posting off topic a bit to help you:

Since renaming solves your error however I'd suggest you look into Microsoft's 'Power Toys' @ https://github.com/microsoft/PowerToys as they include a bulk file renamer which will work as a stop gap solution until or if the error in PDF Arranger is dealt with.

While JPGs are always some type of JPEG they don't have to follow the baseline always; there's different ways to encode them. This is why knowing the encoder would be useful, however renaming the file shouldn't change the library PDF Arranger uses to import them. In general the JPGs that use a different compression are still readable by most graphic viewers.
(For example XnView supports https://github.com/google/guetzli as JPG compression beyond the standard.)

**Comment by jeromerobert** [comment] 2023-09-14 12:20
> i just tried changing file extension to jpeg instead of jpg and it imported without problem. tested with 2 different files

@yw4z Perfect, that's a valuable information. Now we know it's a bug with MIME types.

**Comment by yw4z** [comment] 2023-09-14 12:50
@JunglePredator thanks for your help, already using bulk rename utility for renaming. im mostly dealing with png files that has no problems with pdf arranger and less i need to merge jpgs to pdf. ofc better without dealing renaming extension every time

@jeromerobert glad to found right direction. hope this helps. if you cant replicate errors i can help on testing

**Comment by yw4z** [comment] 2023-09-14 19:25
should i do anything? im using latest .zip version already

**Comment by jeromerobert** [comment] 2023-09-16 14:41
I'll prepare an archive with the python interpreter we use in the Windows installer so you could do test on your system. In the meantime could you check your registry to find if `.jpg` is wrongly registered.

See for exemple: https://stackoverflow.com/questions/7894136/is-there-a-way-to-get-an-extension-for-a-given-content-type

Google tell me also about `HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.jpg`.

**Comment by yw4z** [comment] 2023-09-16 15:03
will it work same as portable version because i never use setup versions and mostly prefer zip versions

![Screenshot-20230916174830](https://github.com/pdfarranger/pdfarranger/assets/28517890/50aa7ef3-94ec-4204-a0ce-03fb62c2105b)
![Screenshot-20230916175036](https://github.com/pdfarranger/pdfarranger/assets/28517890/d7d469b6-ee45-4cd9-be34-aab13ad506f6)
![Screenshot-20230916175200](https://github.com/pdfarranger/pdfarranger/assets/28517890/67c59e1c-b66d-420f-b93b-1bc8356b9061)
![Screenshot-20230916175209](https://github.com/pdfarranger/pdfarranger/assets/28517890/85273a7a-6b28-4583-b22a-c1070dcb406a)
![Screenshot-20230916175227](https://github.com/pdfarranger/pdfarranger/assets/28517890/ea39fae7-2e19-4916-ad13-484336463a20)
![Screenshot-20230916175234](https://github.com/pdfarranger/pdfarranger/assets/28517890/02083c3d-50a0-414b-a50b-9a90d07d1491)
![Screenshot-20230916175414](https://github.com/pdfarranger/pdfarranger/assets/28517890/35253397-59d0-4b57-a9fe-c79d96109757)
![Screenshot-20230916175420](https://github.com/pdfarranger/pdfarranger/assets/28517890/2d410bfb-dc1d-44f3-a723-30dbd0624eed)
![Screenshot-20230916174434](https://github.com/pdfarranger/pdfarranger/assets/28517890/e336d06f-9681-4d5e-8b0d-221dd155981b)
![Screenshot-20230916174453](https://github.com/pdfarranger/pdfarranger/assets/28517890/f8dea74e-c954-426e-8501-8d4b41d36274)
![Screenshot-20230916174818](https://github.com/pdfarranger/pdfarranger/assets/28517890/def0216b-ce89-4ee2-8bee-2a6c9fe4d573)

**Comment by jeromerobert** [comment] 2023-09-16 15:36
The `image/jpg` in `HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.jpg` is suspect but we need to cross check with a Windows system where PDF Arrranger is working properly (and I have no Windows box right now).

Here is the archive:
https://www.transferxl.com/download/08Nrmr6gftFjW (link will die in a week)
SHA256: b1f468e28a5075fd8ade03eee60cbb970bb971d09c819613c5af15874fc0018f

Untar it, open a console in `mingw64\bin` then run:
 ```
 python3.exe -c "import mimetypes ; print(mimetypes.guess_type('foo.jpg'))"
 ```
 And give use the output.

**Comment by yw4z** [comment] 2023-09-16 16:34
output is just
('image/jpg', None)

i was expected much more detailed output :)

**Comment by jeromerobert** [comment] 2023-09-16 17:15
It confirm what I said in https://github.com/pdfarranger/pdfarranger/issues/937#issuecomment-1719436153

**Comment by kbengs** [comment] 2023-09-16 18:04
My Windows has `image/jpeg` in `HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.jpg` and import of image works fine.
If I change it to `image/jpg` import of image fails with the message in yw4z initial post.

**Comment by yw4z** [comment] 2023-09-16 18:34
my problem solved if i change that value to image/jpeg. but why that key is image/jpg on my system and is that default

**Comment by JunglePredator** [comment] 2023-09-17 04:32
Reg file for hkey local machine software classes jpg (couldn't attach because of github's security I assume):

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.jpg]
@="jpegfile"
"Content Type"="image/jpeg"
"PerceivedType"="image"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.jpg\OpenWithList]

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.jpg\OpenWithProgids]
"jpegfile"=""
"Microsoft.PhotoManager.imagetype"=""
"QuickTime.jpg"=hex(0):
"GIMP2.jpg"=""
"SumatraPDF.jpg"=hex(0):
"LibreOffice.Jpg"=" "

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.jpg\PersistentHandler]
@="{098f2470-bae0-11cd-b579-08002b30bfeb}"

**Comment by jeromerobert** [comment] 2023-09-17 08:36
> but why that key is image/jpg on my system

It was probably installed by one of your other applications. Infortunately I don't think there's any way of finding  which one.

> and is that default value for windows?

According to https://stackoverflow.com/questions/33692835/is-the-mime-type-image-jpg-the-same-as-image-jpeg and kbengs and JunglePredator no it's not.

**Closed by jeromerobert** 2023-09-17 08:36 UTC

**Comment by yw4z** [comment] 2023-09-17 10:00
thanks for your help and efforts anyways, at least my problem solved
i tried and installed many image viewers so like you said hard to find which one
have a nice day
