### ISSUE TITLE
Drag and drop breaks in Windows 10 with different scale factors

### ISSUE THREAD

**Issue by csu333** [pdfarranger/pdfarranger#468] opened 2021-04-21 07:35 UTC
I have an issue with PDF arranger under Windows 10. Having 2 screens with different scaling factors, the feature that allows to drag and drop pages in documents only works on the Screen 1. Screen 1 is just the first screen in the enumeration of screens, but not necessarily the primary screen (my primary screen is actually Screen 2).

On Screen 2, when I start dragging, the cursor briefly appears then disappears. 

If I set the same scaling on both screen, the drag and drop works perfectly.

**Comment by dreua** [comment] 2021-04-21 13:02
I'm curious whether that is our bug or Gtk's or even Windows'. Not sure whether I'll find the time to investigate that, though.

**Comment by dreua** [comment] 2021-04-21 21:18
I just gave it a quick try and wasn't able to reproduce on Windows.

**Comment by kbengs** [comment] 2021-04-22 01:34
In a virtual machine I was able to reproduce something similar. When dragging a page on the screen with other scale factor the drag cursor appears to high up. Removing the "GDK_WIN32_USE_EXPERIMENTAL_OLE2_DND" seems to fix the problem. But that again will break dnd between two instances and insert file at drop location will not work either.
So it seems to me that the problem is in GTK. GDK_WIN32_USE_EXPERIMENTAL_OLE2_DND would need to be improved..

**Comment by csu333** [comment] 2021-04-22 05:18
Thank you for having a look. Windows scaling management is clearly crappy, no wonder GTK would have a hard time managing it.

Should I report this issue to the GTK project instead?

This triggers a workaround proposition: How about having a keyboard shortcut to move pages around? I'll introduce a feature request accordingly.

**Comment by dreua** [comment] 2021-04-22 06:20
> Should I report this issue to the GTK project instead?

Yes, that would be great! Ideally add links in both directions, thanks!

**Comment by csu333** [comment] 2021-04-22 06:29
I'm too late, somebody already did: https://gitlab.gnome.org/GNOME/gtk/-/issues/3734

**Comment by dreua** [comment] 2021-04-22 06:36
@pdfarranger Do we close this as not our bug or leave it open until an upstream fix or workaround is applied?

**Comment by jeromerobert** [comment] 2021-04-25 17:17
We can't do anything so let's close it.

**Closed by jeromerobert** 2021-04-25 17:17 UTC
Labels: not our bug

**Comment by dreua** [comment] 2021-09-24 10:05
I just got notified that upstream is working on this, maybe someone here has some spare cycles to help with testing? https://gitlab.gnome.org/GNOME/gtk/-/issues/3734#note_1275968

**Comment by lb90** [comment] 2022-01-15 14:37
Hello everyone! This issue has been fixed in GTK 3.24.31

**Comment by jeromerobert** [comment] 2022-01-17 07:45
I have updated GTK in Github Action for Windows builds. Starting from [this build](https://github.com/pdfarranger/pdfarranger/actions/runs/1706802190), GTK 3.24.31 is used. Would someone mind testing it?

**Comment by kbengs** [comment] 2022-01-18 04:32
Yes it seems to work as it should
