### ISSUE TITLE
Warning message when trying to install (Windows 10)

### ISSUE THREAD

**Issue by lostincoding** [pdfarranger/pdfarranger#778] opened 2022-12-14 09:38 UTC
Hi,

I tried to install the latest version ( pdfarranger-1.9.2-windows-installer.msi ) on Windows 10 and got this message:

Microsoft Defender SmartScreen prevented an unrecognized app from starting.
Publisher: Unknown publisher
![z pdfarranger-001](https://user-images.githubusercontent.com/48190080/207559494-bd5345f4-8ce4-4d48-9bc1-e1261c07c5aa.png)

When i tried a second time, I got a slightly different warning:
SmartScreen can't be reached right now
![z pdfarranger-002](https://user-images.githubusercontent.com/48190080/207559618-b372deca-6b76-4990-92c8-e5d8ede0747d.png)

Is this a known issue? Is it because the publisher is unknown ?

**Comment by dreua** [comment] 2022-12-14 16:50
This is expected behavior because one here felt like buying a code signing certificate just to make Windows happy. The second is either a bug in Windows or your internet connection failing, nothing we can do about that I'm afraid. Shall we close this as not a bug?

**Closed** 2022-12-15 08:29 UTC
Labels: question, Windows
