### ISSUE TITLE
Open the right-click context menu when "Document key" is pressed on the keyboard

### ISSUE THREAD

**Issue by bagajohny** [pdfarranger/pdfarranger#1007] opened 2023-11-29 02:26 UTC
Right now the only way to open the context menu is to right-click on the pages of PDF. I want to request an additional way to do this. 

When we select a page in the opened PDF file and press the Document key/ Right-click key then it should open the context menu.

Here is the mentioned key on the keyboard
![image](https://github.com/pdfarranger/pdfarranger/assets/101859073/782a062a-dc2b-42cc-a5e4-9a0dea04f84a)

And it should open this context menu
![image](https://github.com/pdfarranger/pdfarranger/assets/101859073/e6dbf362-b7f1-4895-8500-f5132c9305ba)

**Comment by bagajohny** [comment] 2023-11-29 02:37
Or you can also add a keyboard shortcut for the "Split Pages" option in the context menu. I usually open the context menu for this particular option.

**Comment by dreua** [comment] 2023-11-29 11:03
Duplicate of #915 thanks for bringing it up again. Iirc this once worked and stopped working at some point.

**Comment by dreua** [comment] 2023-11-29 11:04
> Or you can also add a keyboard shortcut for the "Split Pages" option in the context menu. I usually open the context menu for this particular option.

I don't understand, the Split Pages option is already there in the context menu, I can see it in your screenshot. Did you mean another menu?

**Comment by dreua** [comment] 2023-11-30 10:06
I'm sorry, it seems I was unable to read properly, hiding the unproductive messages.

You can add keyboard shortcuts manually as described in the readme. I would be fine with adding one to each function by default, too, but some folks and iirc Gnome guidelines say thats too much.

What would be your preferred (and still unused) shortcut?

What do the others think about adding this one by default?

**Closed** 2023-12-03 10:46 UTC
Labels: UX
