### ISSUE TITLE
Create Booklet from multiple pages and vice versa

### ISSUE THREAD

**Issue by javadevelopment4** [pdfarranger/pdfarranger#438] opened 2021-03-21 10:13 UTC
It would be great if someone builds or provide the following options

1) Convert A4 PDF to Booklet PDF
2) Convert Booklet PDF to A4 PDF 

Booklet to A4 PDF Example - https://www.sejda.com/split-pdf-down-the-middle
PDF to Booklet - https://www.bookletcreator.com/

**Comment by dreua** [comment] 2021-03-21 21:47
- We are not building such specific features as "A4 only". It has to be valuable to all users, not just you, therefore it must support different page sizes.
- Splitting is already supported, so all that is left would be an automated reordering of the booklet pages, correct?
- Joining pages is not supported at yet. If we are going to do it, this would be the first step and should be tracked as a first separate issue imo.
- Let's give this 3 weeks. If nothing productive comes up it should be closed and tagged `stale feature`.

**Comment by dreua** [comment] 2021-03-27 21:58
I'm not sure I understand those issues correctly, is this actually a duplicate of #246 ?

**Comment by angsch** [comment] 2021-03-28 09:22
> I'm not sure I understand those issues correctly, is this actually a duplicate of #246 ?

No, it is mostly about page reordering. You pile a bunch of landscape pages, fold them in the middle and want to read them as a book. I see two ways of realizing the booklet.
- Reorder the pages, export the PDF and use the printer options to print 2 pages onto 1.
- Reorder the pages, glue pairs of pages together and then print.

I assume that the second option is easier in practice due to duplex printing and sorting of the printed pages.

A dedicated feature for the second option is in my opinion a bit too specific, but I think a page reordering functionality could be useful. If you want to create a booklet using the second option, you would have to do two steps.

**Comment by dreua** [comment] 2021-03-28 10:28
That really sounds like something that would be more convenient in the printing dialog because the booklet PDF will be very useless in a normal PDF viewer. (Hard to read or check without printing it.)

**Comment by dreua** [comment] 2021-03-28 10:31
A general page reordering feature sounds good to me. This could replace/refine the paste interleaved functions, too. I think there were also requests for other paste interleave functions like every third or forth page. (Maybe in another issue tracker, could have been qpdf.)

**Comment by nicos68** [comment] 2021-05-19 22:05
I'm in the hunt for basic open source imposition software in the likes of [BookMaker](https://www.devalipi.com/moreinfobm.html), with crop marks being a welcome bonus. Your software looks like a solid basis and I could implement that on top of it, but I see you are questioning the direction the project is going to, so I'm hesitating between either just start from your project and go my own way or try to stick with your project and produce something you could integrate. What would be your advice ?

**Comment by dreua** [comment] 2021-05-20 02:36
@nicos68 does your question go beyond the feature requested by @javadevelopment4 in the top post? If yes, please create a new issue to discuss it. It may still be quite hard to answer without in depth discussion but at least it won't clutter this issue.

I don't decide this on my own, but I think a PR adding the feature requested here is likely to be merged, given that it is maintainable and is reasonably well integrated in the current UX/UI.

**Comment by angsch** [comment] 2021-08-11 17:19
Pending tasks for the booklet feature

- [ ] Improve rendering (see #500)
- [ ] Support cropped, scaled and rotated pages
- [ ] Positioning of the newly inserted booklet pages
- [ ] Conversion from a booklet to normal pages

The last point is so specific that I would go only for a page reordering. Then a user has to do two actions, a split of the booklet pages, and then a reordering.

**Comment by Davexx** [comment] 2021-08-18 17:24
Joining pages together would complement the split page feature and be very useful.  I hope you are able to implement this. Thanks for a well-designed and robust tool!

**Comment by mara004** [comment] 2021-08-29 11:13
> Joining pages together would complement the split page feature and be very useful.

Actually this feature is not quite about merging pages or N-up, it's really just booklet creation for printing, so please don't have too high expectations at this point.

**Comment by Davexx** [comment] 2021-08-29 16:12
Ahh, Thank for clarifying that.  No high expectations, grateful for what you have built so far.
Hopefully this feature can be added to a user wish list and maybe considered for development some day.

Cheers!

**Comment by mara004** [comment] 2021-08-29 16:32
> Hopefully this feature can be added to a user wish list and maybe considered for development some day.

Yeah, I've just noticed this feature is in fact already in development: https://github.com/pdfarranger/pdfarranger/pull/440

**Comment by kbengs** [comment] 2024-12-27 05:07
>     Convert A4 PDF to Booklet PDF

This was implemented in 1.8.0

>     Convert Booklet PDF to A4 PDF

This is implemented and will be in next release (1.12.0 ?)

**Closed by kbengs** 2024-12-27 05:07 UTC
Labels: feature
