### ISSUE TITLE
Namespace Poppler not Available - Windows

### ISSUE THREAD

**Issue by acorreya** [pdfarranger/pdfarranger#812] opened 2023-01-19 18:07 UTC
Describe the bug
----------------

PDF Arranger had been working well till a week back when it shows the below error on opening. I am not sure what triggered this because there has been no Win updates recently. Tried both 1.9.2 msi and portable, went back up to 1.9.0 too. Makes me think it has something to do with windows. Might be related to Issue #200 

![pdf arranger error](https://user-images.githubusercontent.com/3225091/213524362-e58c74cf-a050-4743-9315-9d6c486ede08.png)

To Reproduce
------------

Install with MSI or use standalone. Open the executable. BAM!

Expected behavior
-----------------

Opens up the main window and works as usual.

System and Versions
-------------------

-   PDF Arranger version: 1.9.2 to 1.9.0 
-   OS name and version: Windows 10 Pro 22H2, OS Build: 19045.2364, Windows Feature Experience Pack 120.2212.4190.0. 
-   Hardware: AMD Ryzen 7 5700U with Radeon 1.80 GHz, 16 GB

**Comment by kbengs** [comment] 2023-01-19 18:13
Could you test the latest development build found here:
https://github.com/pdfarranger/pdfarranger/actions/runs/3918844334

Do you see that same issue with that too?

**Comment by acorreya** [comment] 2023-01-19 19:45
It worked! I got to test only the MSI though because the portable did not unzip right because of "unspecified error" on every other file.

But then Whoa! DARK Mode ❤️

**Comment by jeromerobert** [comment] 2023-01-19 20:43
Duplicate of #645

**Closed by jeromerobert** 2023-01-19 20:43 UTC
