### ISSUE TITLE
Cannot start on Windows with zlib1.dll installed in C:\WINDOWS\system32

### ISSUE THREAD

**Issue by boythere** [pdfarranger/pdfarranger#300] opened 2020-10-13 10:16 UTC
From version (1.4.2, 1.6.2], it shows an error dialog and exits immediately.

<img width="308" alt="screenshot" src="https://user-images.githubusercontent.com/7233253/95848008-0709f480-0d80-11eb-96b3-df7cc997246f.png">

**Comment by angsch** [comment] 2020-10-13 14:16
Hi,
The bottom part of the error message is chopped of. Could you please provide a screenshot with the full error message?

**Comment by boythere** [comment] 2020-10-14 02:00
<img width="308" alt="Screenshot2" src="https://user-images.githubusercontent.com/7233253/95934684-09ae2d80-0e04-11eb-9dcc-cd8dcf716177.png">

**Comment by boythere** [comment] 2020-10-14 07:30
Here are some tests on my laptop.

```
Powershell> c:\msys64\mingw64\bin\python3.exe
Python 3.8.6 (default, Oct  1 2020, 13:01:33)  [GCC 10.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\msys64\mingw64\lib\python3.8\site-packages\gi\__init__.py", line 40, in <module>
    from . import _gi
ImportError: DLL load failed while importing _gi: The specified procedure could not be found.
```

**Comment by boythere** [comment] 2020-10-14 09:15
Good news, guys! I get a way to workaround.

**copy pdfarranger-1.6.2\zlib1.dll to pdfarranger-1.6.2\lib\zlib1.dll**

You know why? I found some useful debug messages. I've pasted focused lines here.

```
3c7c:26d0 @ 09036000 - LdrpSearchPath - ENTER: DLL name: zlib1.dll
3c7c:26d0 @ 09036000 - LdrpComputeLazyDllPath - INFO: DLL search path computed: C:\Users\Name\Downloads\pdfarranger-1.6.2\lib;C:\WINDOWS\SYSTEM32;C:\WINDOWS\system;C:\WINDOWS;
3c7c:26d0 @ 09036000 - LdrpResolveDllName - ENTER: DLL name: C:\Users\Name\Downloads\pdfarranger-1.6.2\lib\zlib1.dll
3c7c:26d0 @ 09036000 - LdrpResolveDllName - RETURN: Status: 0xc0000135
3c7c:26d0 @ 09036000 - LdrpResolveDllName - ENTER: DLL name: C:\WINDOWS\SYSTEM32\zlib1.dll
3c7c:26d0 @ 09036000 - LdrpResolveDllName - RETURN: Status: 0x00000000
3c7c:26d0 @ 09036000 - LdrpSearchPath - RETURN: Status: 0x00000000
...
3c7c:26d0 @ 09039140 - LdrpNameToOrdinal - WARNING: Procedure "deflateSetHeader" could not be located in DLL at base 0x0000000180000000.
3c7c:26d0 @ 09039140 - LdrpReportError - ERROR: Locating export "deflateSetHeader" for DLL "C:\Users\Name\Downloads\pdfarranger-1.6.2\libgio-2.0-0.dll" failed with status: 0xc0000139.
(3c7c.26d0): Unknown exception - code c0000139 (first chance)
3c7c:26d0 @ 09039140 - LdrpGenericExceptionFilter - ERROR: Function LdrpSnapModule raised exception 0xc0000139
	Exception record: .exr 000000000062A170
	Context record: .cxr 0000000000629C80
```

The working path of the application may be changed by GTK+3,
so the DLL search path computed is like C:\Users\Name\Downloads\pdfarranger-1.6.2\lib. 
We know that the right search path should be C:\Users\Name\Downloads\pdfarranger-1.6.2.

As the result, Windows falls back to locate my zlib1.dll in C:\WINDOWS\system32. **It is a DLL hell (wrong version).**

Finally, zlib1 failed to call deflateSetHeader() in libgio-2.0-0.dll.

**Comment by boythere** [comment] 2020-10-14 09:41
One more thing. The working path should be set correctly.

<img width="282" alt="Screenshot3" src="https://user-images.githubusercontent.com/7233253/95971897-5d406b80-0e44-11eb-8741-ee61f5d1fc51.png">

**Comment by angsch** [comment] 2020-10-14 09:52
It's great that you managed to find a workaround. If it is a DLL issue, you can try the zip release instead of the msi release. It ships the required DLLs and due to the load order of DLLs on Windows there should not be any such issues.

I tried to reproduce the issue on two Windows systems. On one, the msi build works. On the other, the msi build yields me the issue raised above (zip release worked).

**Comment by jeromerobert** [comment] 2020-10-14 18:44
@boythere Thanks for the investigations !

> so the DLL search path computed is like C:\Users\Name\Downloads\pdfarranger-1.6.2\lib

In https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order and particularly I though *"the directory from which the application loaded"* was the folder containing the `pdfarranger.exe`. But from what you say I guess it can also be the folder containing the DLL which is loading an other DLL. Here `pdfarranger.exe` is probably loading `lib/zlib-cpython-38.dll` which in turn is trying to load `zlib1.dll` from `lib`.

If `zlib1.dll` was loaded by `libcairo-2.dll` or `qpdf28.dll` or `libxml2-2.dll` it should be search from the pdfarranger root folder, not from `lib`. So may be we can fix that by changing the order of the python imports. However I admit it would not be very safe / maintainable.

There's one thing I still don't understand, that's why there's no problem with the .zip file.

> One more thing. The working path should be set correctly.

Indeed. Moreover that would fix this issue when `SafeDllSearchMode` is disabled.

**Comment by boythere** [comment] 2020-10-15 02:07
@angsch @jeromerobert

I am sure that zlib1.dll is loaded by lib/zlib-cpython-38.dll, after I go through logs. Here is the loading order.

1. C:\Users\Name\AppData\Local\Programs\pdfarranger\pdfarranger.exe
2. ntdll.dll
3. C:\WINDOWS\System32\KERNEL32.DLL
4. C:\Program Files\AVAST Software\Avast\aswhook.dll
5. C:\WINDOWS\System32\KERNELBASE.dll
6. C:\WINDOWS\System32\msvcrt.dll
7. C:\WINDOWS\System32\SHLWAPI.dll
8. C:\WINDOWS\System32\USER32.dll
9. C:\WINDOWS\System32\win32u.dll
10. C:\WINDOWS\System32\GDI32.dll
11. C:\WINDOWS\System32\gdi32full.dll
12. C:\WINDOWS\System32\msvcp_win.dll
13. C:\WINDOWS\System32\ucrtbase.dll
14. C:\Users\Name\AppData\Local\Programs\pdfarranger\libpython3.8.dll
15. C:\WINDOWS\System32\ADVAPI32.dll
16. C:\WINDOWS\System32\sechost.dll
17. C:\WINDOWS\System32\RPCRT4.dll
18. C:\WINDOWS\System32\WS2_32.dll
19. C:\Users\Name\AppData\Local\Programs\pdfarranger\libwinpthread-1.dll
20. C:\WINDOWS\SYSTEM32\VERSION.dll
21. C:\WINDOWS\System32\IMM32.DLL
22. C:\WINDOWS\SYSTEM32\CRYPTSP.dll
23. C:\WINDOWS\system32\rsaenh.dll
24. C:\WINDOWS\System32\bcrypt.dll
25. C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
26. C:\WINDOWS\System32\bcryptPrimitives.dll
27. C:\Users\Name\AppData\Local\Programs\pdfarranger\lib\zlib-cpython-38.dll
28. C:\WINDOWS\SYSTEM32\zlib1.dll
29. ...

By the way, the searching path shown in logs that time is: 

1. C:\Users\Name\AppData\Local\Programs\pdfarranger\lib
2. C:\WINDOWS\SYSTEM32
3. C:\WINDOWS\system
4. C:\WINDOWS
5. . (I supposed it is working path)
6. ...

It shows that the application always FALLS BACK to load .\zlib1.dll if no zlib1.dll is found in Path 1-4. Fallback would not be your expectation. So, both releases wouldn't work when zlib1.dll existed in the system32 folder. 

As far as I know, the difference between two releases is the working path. If `Start in` is set, they two would be same.

**Comment by angsch** [comment] 2020-10-26 10:15
On my machine both Gtk and cairo require additional DLLs or modifications to $PATH, which are apparently not handled by cx_Freeze. From https://cx-freeze.readthedocs.io/en/latest/faq.html:
> A common problem is that cx_Freeze hasn’t automatically detected that a file needs to be copied. Modules that your code imports are detected, but if they’re dynamically loaded - e.g. by a plugin system - you have to tell cx_Freeze about them.

Other projects approach this issue in one of the two ways.
1) The import statements are delayed and moved into the routines that actually need the imports. This could be sufficient for cairo. I do not see how we can make this work with gi.
2) The cx_Freeze setup script is revised by adding DLLs and setting paths `os.environ[...]`. No idea how maintainable this is.

**Comment by jeromerobert** [comment] 2020-10-26 20:43
Status: I'm currently working on this issue. Moving zlib1.dll to `lib` allow to fix it. I also applied a patch to cx_Freeze to have a running folder in the shortcut. I'm currently trying to make a new Docker image but finding a wine version which work is difficult.

> On my machine both Gtk and cairo require additional DLLs

@angsch Which DLLs are missing ?

**Comment by angsch** [comment] 2020-10-27 16:05
Using [listdlls](https://docs.microsoft.com/en-us/sysinternals/downloads/listdlls):
- libintl-8.dll
- liblcms2-2.dll

I don't know if the output of listdlls respects the load order. If that is the case, the load order of the native build and the msi build deviate at a few cases. In particular the order of qpdf28.dll and the gi-related dlls are swapped.

**Comment by jeromerobert** [comment] 2020-10-29 21:33
> I don't know if the output of listdlls respects the load order. If that is the case, the load order of the native build and the msi build deviate at a few cases. In particular the order of qpdf28.dll and the gi-related dlls are swapped.

Interesting & odd. I have no clues why this order change.

> The cx_Freeze setup script is revised by adding DLLs and setting paths os.environ[...].

I'm afraid not. PATH is always search after system folder. And when SafeDllSearchMode is enabled the current folder is always search after system folder. The only way to fix all those kind of issues is having each DLL in the folder of the first .exe or DLL which load it.

**Comment by jeromerobert** [comment] 2020-10-29 21:37
* Fixed shortcut "Start in": https://github.com/jeromerobert/cx_Freeze/commit/a4f7ab5a1575700a82f7e440f59d7f3840d7da71
* Moved zlib1.dll: 2ec0dd0

**Comment by jeromerobert** [comment] 2020-10-29 21:38
See also https://github.com/marcelotduarte/cx_Freeze/issues/366

**Comment by jeromerobert** [comment] 2020-10-29 21:41
I don't plan to spend more time on that issue. Doing this for all DLL and ensure it works is too much work. Moreover `SafeDllSearchMode` makes no sens if applications install DLLs in c:\Windows\System32. So unless someone wants to add something I'm going to close this issue.

**Comment by angsch** [comment] 2020-11-04 11:39
The fix works on the system where I previously got the error. I support closing the issue.

I will investigate the disparity with the other DLL when I have time and will get back if there is an issue.

**Closed** 2020-11-05 15:36 UTC
