### ISSUE TITLE
TypeError: [''] when trying to export a pdf. -> file is not saved

### ISSUE THREAD

**Issue by kbengs** [pdfarranger/pdfarranger#384] opened 2021-01-11 16:38 UTC
![typeerror](https://user-images.githubusercontent.com/60842129/104204427-f2e49a80-5435-11eb-9b50-6d1d7d1fb4ef.jpg)

python3 -m pdfarranger
Traceback (most recent call last):
  File "/home/kb/pdfarranger/pdfarranger/pdfarranger.py", line 695, in choose_export_pdf_name
    self.save(mode, file_out)
  File "/home/kb/pdfarranger/pdfarranger/pdfarranger.py", line 157, in wrapper
    func(*args, **kwargs)
  File "/home/kb/pdfarranger/pdfarranger/pdfarranger.py", line 763, in save
    m = metadata.merge(self.metadata, self.pdfqueue)
  File "/home/kb/pdfarranger/pdfarranger/metadata.py", line 84, in merge
    load_from_docinfo(meta, doc)
  File "/home/kb/pdfarranger/pdfarranger/metadata.py", line 72, in load_from_docinfo
    meta.load_from_docinfo(doc.docinfo)
  File "/home/kb/.local/lib/python3.8/site-packages/pikepdf/models/metadata.py", line 382, in load_from_docinfo
    self._setitem(qname, val, True)
  File "/home/kb/.local/lib/python3.8/site-packages/pikepdf/models/metadata.py", line 725, in _setitem
    raise TypeError(val)
TypeError: ['']

Same happens if I try to open "Edit properties"

This is with pdfarranger master. Pikepdf-2.3.0

**Comment by jeromerobert** [comment] 2021-01-12 21:32
I cannot reproduce it. Could you share the PDF file ?

**Comment by kbengs** [comment] 2021-01-13 03:26
Unfortunately I can't share it.
The problem only occurs on this file. But it's not a new problem, also pikepdf 1.10.3 and pdfarranger 1.4.2 has the same error.

If we also catch typeerror, so the code in metadata.py looks like this:
```
def load_from_docinfo(meta, doc):
    """
    wrapper of pikepdf.models.PdfMetadata.load_from_docinfo with a workaround
    for https://github.com/pikepdf/pikepdf/issues/100
    """
    try:
        meta.load_from_docinfo(doc.docinfo)
    except (NotImplementedError, TypeError):
        # DocumentInfo cannot be loaded and will be lost. Not a that big issue.
        traceback.print_exc()
```
Then only these lines are printed:
```
Traceback (most recent call last):
  File "/home/kb/pdfarranger/pdfarranger/metadata.py", line 72, in load_from_docinfo
    meta.load_from_docinfo(doc.docinfo)
  File "/home/kb/.local/lib/python3.8/site-packages/pikepdf/models/metadata.py", line 382, in load_from_docinfo
    self._setitem(qname, val, True)
  File "/home/kb/.local/lib/python3.8/site-packages/pikepdf/models/metadata.py", line 725, in _setitem
    raise TypeError(val)
TypeError: ['']
```
But the file is at least exported then and it looks fine.
Is there anything more that could be done to this?

**Comment by jeromerobert** [comment] 2021-01-13 20:23
Let's go with your patch, this will be enough until it get fixed in pikepdf.

**Closed** 2021-01-14 20:40 UTC
