### ISSUE TITLE
Adding PDF fails with QPDF__copyForeign called with direct object handle

### ISSUE THREAD

**Issue by ChristianNext** [pdfarranger/pdfarranger#524] opened 2021-09-05 12:07 UTC
Adding a PDF does fail for some PDFs on version 1.7.1-0~hirsute0, Ubuntu 21.04. Issue occurs with only a few PDFs, for example a monthly recurring PDF bill has the same issue every time.

### Reproduce

1. Open PDF1 with pdfarranger
2. drag-drop a single page PDF2 into PDF1
3. save PDF1
4. save fails with pop-up "QPDF__copyForeign called with direct object handle"

### Workaround

1. Open  PDF2 in LibreOffice Draw
2. save as PDF3
3. drag-drop  PDF3 into the PDF1
4. save PDF
5. save works

I upgraded to 1.7.1-0 by adding the PPA https://launchpad.net/~linuxuprising/+archive/ubuntu/apps.

**Comment by dreua** [comment] 2021-09-05 12:18
Hey, thanks for the report. Can you share a file causing the issue with us? My email is visible in my profile in case you don't want to attach it here.

Otherwise I'd like you to try the flatpak version once to rule out that this is already fixed with the latest pikepdf / qpdf.

**Comment by dreua** [comment] 2021-09-05 21:14
This might be fixed by https://github.com/pdfarranger/pdfarranger/pull/485/commits/9ce7f05cb16ea1f714ed43baef874043848bc84f (not released yet).

**Comment by jeromerobert** [comment] 2021-09-06 17:19
9ce7f05 is not in PDF Arranger, it's probably the commit from my branch before the merge. You are talking about abb3f0250e016a4d51a504952a10f52adad03d60. Anyway it's not related to this issue because it's a fix for c8e58d92fb6d280e12daff1c1688c9aa2a18b2fe which was added after 1.7.1 (also unreleased). We definitly need that *PDF2*.

**Comment by dreua** [comment] 2021-09-06 18:20
Thanks @jeromerobert , it seems like I wasn't paying enough attention here, you are absolutely right. I got the PDF but could not reproduce on my system. I guess I could share it with you but I'd like to wait for confirmation by @ChristianNext before I do that.

**Comment by jeromerobert** [comment] 2021-09-06 18:39
@ChristianNext Could you run PDF Arranger from a terminal, reproduce the bug and paste the full error message here. There should be a stack trace that will help us.

**Comment by ChristianNext** [comment] 2021-09-07 09:42
I am on Ubuntu 21.04 
- pdfarranger/hirsute,hirsute,now 1.7.1-0~hirsute0 all [installed]
- python3-pikepdf/hirsute,now 1.17.3+dfsg-5ubuntu1 amd64 [installed,automatic]
- libqpdf28/hirsute,now 10.3.1-1 amd64 [installed,automatic]

Here is the stack trace 
```
$ pdfarranger
Traceback (most recent call last):
  File "/home/myuser/.local/lib/python3.9/site-packages/pdfarranger/pdfarranger.py", line 809, in choose_export_pdf_name
    self.save(mode, file_out)
  File "/home/myuser/.local/lib/python3.9/site-packages/pdfarranger/pdfarranger.py", line 158, in wrapper
    func(*args, **kwargs)
  File "/home/myuser/.local/lib/python3.9/site-packages/pdfarranger/pdfarranger.py", line 883, in save
    exporter.export(self.pdfqueue, to_export, file_out, mode, m)
  File "/home/myuser/.local/lib/python3.9/site-packages/pdfarranger/exporter.py", line 179, in export
    pdf_output.pages[-1].Annots = pdf_output.copy_foreign(pdf_temp.pages[0].Annots)
RuntimeError: QPDF::copyForeign called with direct object handle
```

**Comment by jeromerobert** [comment] 2021-09-07 10:18
This is not the stack trace of version 1.7.1. You installed a version from the main branch with pip which contains abb3f02 but not c8e58d9. dreua is right, this bug is a duplicate of #484.

**Comment by ChristianNext** [comment] 2021-09-07 10:37
Tks again for looking into this.

```
sudo apt show pdfarranger
Package: pdfarranger
Version: 1.7.1-0~hirsute0
```
I seem to have two versions
```
md5sum /home/myuser/.local/bin/pdfarranger  /usr/bin/pdfarranger
884058a5f8ba33aaee68208bed2f2d54  /home/myuser/.local/bin/pdfarranger
7d6d90f054c5865a5cbcec815652bccc  /usr/bin/pdfarranger
```
Both show the same stack (same line numbers).

How can I make sure I test the latest version? Why does "apt show" display something else??

**Comment by jeromerobert** [comment] 2021-09-07 11:31
Just run `pip uninstall pdfarranger`.

**Closed** 2021-11-11 20:48 UTC
