### ISSUE TITLE
Not remembering window position

### ISSUE THREAD

**Issue by yw4z** [pdfarranger/pdfarranger#719] opened 2022-09-17 22:53 UTC
Hi, thanks for great app
i'm using app on windows with multi monitor setup
my secondary monitor on left side and app always starts on my secondary monitor even if i close window on primary monitor
secondary monitor is 1080p, primary monitor is 1440p

**Comment by jeromerobert** [comment] 2022-09-18 08:42
This needs to implemented here:
* `pdfarranger/config.py`
* `pdfarranger/pdfarranger.py` (`__create_main_window` and `close_application`)

Gtk provide ways to get/set the screen:
* <https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/Window.html#Gtk.Window.set_screen>
* <https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/Window.html#Gtk.Window.get_screen>

Unfortunnalty [Gdk.Display.get_screen](https://lazka.github.io/pgi-docs/#Gdk-3.0/classes/Display.html#Gdk.Display.get_screen) is deprecated and always return the default screen.

<https://docs.gtk.org/gtk3/method.Window.get_position.html> suggest that the mirror method of `get_position` is not `set_position` (the one we currently use) but `move`. This is also what <https://stackoverflow.com/questions/39367246/select-certain-monitor-for-going-fullscreen-with-gtk> suggest. So may be just replacing `set_position` by `move` in `__create_main_window` would work.

I don't have multiscreen setup so I won't personnaly work on that issue. Also this can be tricky as we have to make it work with all window manager, display manager, and system and do not break what already works. That's why I tag it 1.10 and not 1.9.x.

**Comment by dreua** [comment] 2022-09-22 10:57
FTR: It works fine on Linux (Fedora with Gnome on X11). Can we just recommend that the users switch to Linux? I'm not sure someone here wants to fix in on Windows...

**Comment by kbengs** [comment] 2022-09-23 15:26
I tested this today in Windows with two 1080p screens and there it worked fine. "Remember window position on screen" was implemented in 1.8.0. @yw4z I guess you are not using anything older than that..?

**Comment by kbengs** [comment] 2022-09-24 04:04
I am able to reproduce it in Window 7 in Virtualbox.

Interestingly, if I create a zip or msi (from current main) on my machine it will not have the issue.

My machine has libqpdf 10.0.1, pikepdf 2.16.1, GTK 3.24.16 och Python 3.8.2

Also 1.8.2 does not seem to have this issue.. (the officially built version)

**Comment by kbengs** [comment] 2022-12-10 07:31
With GTK 3.24.35 the problem seems to be gone. @jeromerobert ie when `mingw-w64-x86_64-gtk3` is updated

**Comment by yw4z** [comment] 2022-12-10 12:16
yes using libgdk-3.0.dll from 1.8.2 also resolved issue for me. waiting a new version to test with fix, thanks for help

**Comment by yw4z** [comment] 2022-12-10 12:16
yes using libgdk-3.0.dll from 1.8.2 also resolved issue for me. waiting a new version to test with fix, thanks for help

**Comment by kbengs** [comment] 2022-12-10 12:30
@yw4z You can find a zip/msi here https://github.com/pdfarranger/pdfarranger/actions/runs/3663871923 where the issue should be fixed. Would be nice if you can test it.

**Comment by yw4z** [comment] 2022-12-10 17:34
thanks again looks like its fixed,
its minor issue but its not %100 correct. if i move window to edge of screen it always put a gap between edge and window ofc its not neccesary. its opening correct monitor right now

**Closed** 2022-12-11 13:24 UTC
Labels: Windows
