### ISSUE TITLE
drag and drop of pages to reorder fails on a multiscreen windows setup

### ISSUE THREAD

**Issue by devkral** [pdfarranger/pdfarranger#618] opened 2022-01-20 10:58 UTC
Describe the bug
----------------
It seems that pdfarranger fetches the scaling settings from the monitor with the lowest index.
This scaling is used for drag and drop operations to move pages.
If the pdfarranger window is moved to a monitor with an higher index and the scaling settings of the monitors doesn't match, drag and drop operations won't work (the drop indication is out of place)
This is maybe a gtk bug. This bug doesn't affect dropping files into pdfarranger, this works normal.

To Reproduce
------------
Change the element scaling setting (of text/elements not the custom scaling) of the monitor with the lower index to 150%, leave the element scaling option of the monitor with the higher index on 100%. Move the pdfarranger window to this monitor.

Drag and drop of pages to reorder works as normal.

Then move the pdfarranger window to the window with the higher index.

Dragging and dropping pages to reorder will be off place 

Expected behavior
-----------------

Drag and drop of pages should work

Input files
-----------

tested with multiple pdf files

Screenshots
-----------
Maybe later

System and Versions
-------------------

-   PDF Arranger 1.8.2, windows msi
-   Windows 10

**Comment by dreua** [comment] 2022-01-20 12:59
Duplicate of #468 , please check the Windows built linked there works for you let us know.

**Closed by dreua** 2022-01-20 12:59 UTC
Labels: Windows
