### ISSUE TITLE
Exporting on Windows 10/11 in version 1.11.0 takes very long

### ISSUE THREAD

**Issue by rwxguo** [pdfarranger/pdfarranger#1110] opened 2024-08-20 03:47 UTC
Describe the bug
----------------

The process of exporting PDF is never completed in version 1.11.0, but work properly <= 1.10.0

To Reproduce
------------

1.  Open pdfarranger
2.  Drag & Drop few PDFs into the application
3.  Export as single PDF (Shift + Ctrl + E)
4.  The application is halting, keep using CPU and memory.

Expected behavior
-----------------

The single PDF should be exported properly.

Input files
-----------

The same issue happen on every pdf format.

Screenshots
-----------

![圖片](https://github.com/user-attachments/assets/e2edbb42-aad2-4b65-9f9d-18daae8297fc)

System and Versions
-------------------

-   PDF Arranger 1.11.0, downloaded from Github Release page
-   OS Windows 10 Enterprise LTSC, 21H2, 19044.4529, Windows Feature Experience Pack 1000.19058.1000.0

**Comment by kbengs** [comment] 2024-08-20 15:14
Unfortunately I can't reproduce that issue. Are you sure it is with any PDF? Can you share a PDF where you see the issue?

https://github.com/pdfarranger/pdfarranger/actions/runs/10472311372/artifacts/1832420250
You could try to download the link above. It is the portable version of pdfarranger built with console printing.
If you run it from Windows command prompt it might print out some clues about why it is failing.

**Comment by rwxguo** [comment] 2024-08-22 03:38
Any PDF will cause the issue. Maybe only happen on my PC..

Please find the following screen-cap:

![image](https://github.com/user-attachments/assets/3c0b4bb8-5c02-41b1-887d-3380176cf6bf)

**Comment by kbengs** [comment] 2024-08-25 05:33
It could be that it for some reason loads some wrong dll file.

You could:
*   Get https://docs.microsoft.com/en-us/sysinternals/downloads/listdlls
*   Start PDF Arranger 1.11 with listdlls64.exe -u pdfarranger.exe > dll_list_111.txt
*   Do another list with 1.10 and compare. Or possibly post the list here.

**Comment by rwxguo** [comment] 2024-08-26 04:46
> It could be that it for some reason loads some wrong dll file.
> 
> You could:
> 
>     * Get https://docs.microsoft.com/en-us/sysinternals/downloads/listdlls
> 
>     * Start PDF Arranger 1.11 with listdlls64.exe -u pdfarranger.exe > dll_list_111.txt
> 
>     * Do another list with 1.10 and compare. Or possibly post the list here.

Here it is (I have removed the unnecessary diff and only shows the path):

* [dll_list_110.txt](https://github.com/user-attachments/files/16744130/dll_list_110.txt)
* [dll_list_111.txt](https://github.com/user-attachments/files/16744131/dll_list_111.txt)

**Comment by kbengs** [comment] 2024-08-26 14:09
Thanks but the path part (which you have removed) is actually the interesting part here. :-)  We are looking for dlls loaded from a path other than pdfarranger or pdfarranger/lib. You can also email me at kbengs at hotmail.com then I can compare with my 1.11 dll list.
You could also try `listdlls64.exe pdfarranger.exe > dll_list_111_without_u.txt`

**Comment by rwxguo** [comment] 2024-08-27 09:51
The difference is as follows, thanks! :

![image](https://github.com/user-attachments/assets/5dc11a5f-4909-4076-9f38-4d3428c754ce)

**Comment by kbengs** [comment] 2024-08-27 16:54
:+1: I can't see anything abnormal in the list. I don't have any ideas right now how to troubleshoot this..

**Comment by rwxguo** [comment] 2024-08-28 04:10
Never mind. Maybe my case is a special one. I will keep using 1.10.0. Thanks for your quick response !

**Comment by dreua** [comment] 2024-08-30 08:30
In your first screenshot it looks like it uses 4GB of ram, that is a bit much. In the second it is only about 300 MB which sounds more reasonable. Is the ram usage increasing while it freezes or can you see any pattern there?
Not sure we can debug it further tbh and yes, it seems specific to your system as we don't have any similar reports here.

**Comment by rwxguo** [comment] 2024-08-30 08:52
The memory usage is floating up and down between 300~400 MB to 3~4 GB.

![image](https://github.com/user-attachments/assets/41424c95-9074-4303-96cc-d815ac1913c2)

**Comment by rwxguo** [comment] 2024-08-30 09:13
Hey guys, I would like to let you know that after few minutes leaving the `pdfarranger` running like above, the PDF was finally generated. Then I tired to repeat the same operation and everything can be done immediately, until I restart the `pdfarranger`, I need to wait again, like a warm-up.

**Comment by dgy125** [comment] 2024-09-04 06:17
这个问题我也出现了，WIn11，保存或另存为，均会卡死。

**Comment by rwxguo** [comment] 2024-09-04 06:21
> 这个问题我也出现了，WIn11，保存或另存为，均会卡死。

Translation above: "The same issue happened on my Windows 11. The program were halting there after saving or saving as.."

**Comment by gontera** [comment] 2024-09-21 11:27
I have the same problem here.  PDF Arranger always hangs at exporting any PDF file.  But after I change the UI Language (to "en") in PDF Arranger Preferences, it runs fine without any problem.

Note that my original UI Language setting is "zh_TW".

**Comment by dreua** [comment] 2024-09-21 11:46
Well that sounds like a weird bug somewhere deep down. Thanks for the valuable input @gontera ! If we could make this reproducible somehow that would help a great deal with fixing it. What language settings are you using @rwxguo and @csgrig73 ? Could you retry with english as well?

Could anyone affected try to reproduce this with a publicly available PDF or something you are happy to share here and provide the timing with the two PDf Arranger versions?

**Comment by dreua** [comment] 2024-09-21 12:17
Also could someone report the versions of pikepdf and qpdf as displayed in the about dialog for 1.11.0 and 1.10.0?
There is for example this report for qpdf on windows: https://github.com/qpdf/qpdf/issues/798

**Comment by rwxguo** [comment] 2024-09-21 12:41
I always got the following error when I load a pdf file whatever version I use, any idea ?

![image](https://github.com/user-attachments/assets/57dc4700-c1d6-4689-ab6b-5f060ce5884a)

**Comment by rwxguo** [comment] 2024-09-21 12:46
> Also could someone report the versions of pikepdf and qpdf as displayed in the about dialog for 1.11.0 and 1.10.0? There is for example this report for qpdf on windows: [qpdf/qpdf#798](https://github.com/qpdf/qpdf/issues/798)

1.10.0

* pikepdf 6.2.6
* libqpdf 11.2.0

1.11.0

* pikepdf 8.5.0
* libqpdf 11.6.2

**Comment by dreua** [comment] 2024-09-21 12:58
Thanks! The bug I linked should be already fixed in qpdf 11.2.0 so thats probably not it. My intuition says we should focus on the language settings first, what language are you using @rwxguo and could you try setting PDF Arranger to English and test again?

Unfortunately I don't have a solution on for your gsettings error at hand. (In general it is better copy and paste the errors because it allows search functions to index the text and other users to use it as a search string which is not possible with a screenshot.) It might be something being not in the right location or a path not set to the right value.

**Comment by rwxguo** [comment] 2024-09-21 13:01
I figured out the GSETTINGS error by the following for my WIndows MSYS2

```
GSETTINGS_SCHEMA_DIR=/mingw64/share/glib-2.0/schemas/ /mingw64/bin/python3.exe -m pdfarranger
```

The same issue found even I checkout for 1.10.0, so it might related to other issues rather than the commits between 1.10.0 and 1.11.0... (but compiled 1.10.0 has no such issue)

Will try the language approach and feedback to you.

**Comment by rwxguo** [comment] 2024-09-21 13:29
@dreua 

Finally found which commit caused the issue, for your reference.

```
7ddcfa32eaf5a698d768853f010114541c94ae40 Use Windows language as default language
```

![image](https://github.com/user-attachments/assets/ea3ce185-e8bd-4df2-97f0-0ce663aacc9b)

**Comment by rwxguo** [comment] 2024-09-21 13:43
After I changed my Windows language to `English`, the issue also disappeared.

![image](https://github.com/user-attachments/assets/f485dbc5-67c6-45f5-b4b9-4bbb5cae5c99)

**Comment by kbengs** [comment] 2024-09-21 14:47
Thanks for the info here.

When I run pdfarranger from MSYS2 MSYS shell with language set to zh_CN or zh_TW in preferences dialog (my Windows is English), when saving I get:
```
$ /mingw64/bin/python3.exe -m pdfarranger
Traceback (most recent call last):
  File "C:/msys64/home/kbeng/pdfarranger/pdfarranger/exporter.py", line 247, in wrapper
    func(*args, **kwargs)
  File "C:/msys64/home/kbeng/pdfarranger/pdfarranger/exporter.py", line 485, in export
    export_doc_job(pdf_input, files, pages, mdata, files_out, quit_flag, test_mode)
  File "C:/msys64/home/kbeng/pdfarranger/pdfarranger/exporter.py", line 454, in export_doc_job
    pdf_output = job.create_pdf()
                 ^^^^^^^^^^^^^^^^
MemoryError: std::bad_alloc
```
This is with libqpdf 11.9.1, pikepdf 8.12.0, GTK 3.24.42 and Python 3.11.9 (from about dialog)

 @rwxguo you don't see this error? Could you also post the versions seen in about dialog when you run from MSYS2 MSYS shell ?

**Comment by rwxguo** [comment] 2024-09-21 15:05
Now my Windows Language is English, and I started the program from MSYS2, here is the behavior:

* By default, the menu in pdfarranger is English, can saving properly
* I changed language to zh_CN, the menu is still English, can saving properly
* I quit the program, and restart from MSYS2 again, saving issue
* I changed language back to System default (English), the menu is still Chinese, saving issue
* I quit the program, and restart from MSYS2 again, menu is back to English saving properly

I didn't see the error maybe because when I saw the saving is halting, I just kill the task from my Windows task manager.

libqpdf 11.9.1, pikepdf 9.2.1, GTK 3.24.43 and Python 3.11.10.

**Comment by rwxguo** [comment] 2024-09-21 15:14
New findings:

The issue is related to the Language of the pdfarranger. (changed in pdfarranger preference)

After changing the language, I need to restart the program to active the target language (the menu will become that language)

I have tried zh_CN, zh_TW, ja, kr, es, en:

* Issue found for `zh_CH`, `zh_TW`, `js`, `kr` (Asia characters)
* Issue not found for `en` and `es` 

It doesn't matter which Windows Language you are using, I faced the issue because by default my pdfarranger is using my system default language which is `zh_TW`

**Comment by dreua** [comment] 2024-09-21 15:37
> MemoryError: std::bad_alloc

I'd say you are running out of memory here, have a look at your system resources :wink: (Or maybe allocation is limited by something else.)

This fits with the increased memory usage in the screenshots above and very likely also with long delays. Something is doing something wrong which results in allocation of lots of memory which takes time and either fails when the memory runs out or succeeds after taking a long time. Performance increase on subsequent calls is explainable either due to the stuff needed already being there or due to more readily available RAM (everything else is already compressed or pushed to the pagefile).

@jbarlow83 @jberkenbilt have you heard of anything like this in qpdf or pikepdf on Windows? It's a bit strange, could very well be a different library that has issues with the language setting.

**Comment by kbengs** [comment] 2024-09-21 17:37
> MemoryError: std::bad_alloc

Yeah, if I increase memory on Windows (4GB -> 8GB) I don't see the MemoryError. Instead saving use a lot of memory (up to about 4GB) and saving takes about 20 minutes. The saved PDF looks okay.

Tested a few pikepdf versions:
pikepdf 6.2.6 -> no issue (pdfarranger 1.10.0)
pikepdf 6.2.9 -> no issue
pikpedf 7.0.0 -> issue
pikpedf 8.12.0 -> issue
pikpedf 9.2.1 -> issue (latest pikepdf)

So it looks like the issue is introduced with pikepdf 7.0.0. It does not look like it is related to the job interface (as it is not used with pikepdf 7.0.0)

I'll continue to try to make a minimum example.

**Comment by jberkenbilt** [comment] 2024-09-21 23:29
qpdf is pretty good about memory, particularly in more recent versions, but there are some files that may cause qpdf to use a large amount of memory depending on what the code is doing. In its default mode, qpdf never allocates more than about 2x the size of the largest stream in the file. There are actually tests for this. I can't speak to pikepdf, but memory issues are very often about the way the library is used rather than something in the library itself.

**Comment by kbengs** [comment] 2024-09-28 04:58
The issue can be reproduced with this code:
```
# code run in "MSYS2 MSYS" terminal in Windows
import os
import multiprocessing  # fix 1: do not use multiprocessing
import pikepdf  # fix 2: use pikepdf < 7.0
import gi

gi.check_version('3.10.2')
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk  # fix 3: do not import Gtk

os.environ['LANG'] = 'zh_CN'  # fix 4: use lang other than 'zh_CN', 'zh_TW', 'el', 'he', 'ja', 'ko'

print("pikepdf-" + pikepdf.__version__)

def export_process(*args, **kwargs):
    pdf_input = pikepdf.open('blank.pdf')
    pdf_output = pikepdf.Pdf.new()
    i = 0
    for page in pdf_input.pages:
        pdf_output.pages.append(page)
        print('page', i, 'added')
        #if i == len(pdf_input.pages) - 1:   # fix 5: help the loop to break
        #    break
        i += 1
    print('loop done')
    pdf_output.save("testfile.pdf")
    print('all done')

if __name__ == '__main__':
    ep = multiprocessing.Process(target=export_process)
    ep.start()
    ep.join()

# fix 6: increase memory. Then it will save but will be super slow and use a lot of memory (a few Gb).
```

And output is:
```
$ /mingw64/bin/python3.exe mexample.py
pikepdf-9.2.1
pikepdf-9.2.1
page 0 added
Process Process-1:
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "C:/msys64/mingw64/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:/msys64/home/kbeng/mexample/mexample.py", line 19, in export_process
    for page in pdf_input.pages:
MemoryError: std::bad_alloc
```


Where should the bug be reported? :smiley:

**Comment by dreua** [comment] 2024-09-28 06:28
# fix 7: Don't use Windows :wink:

**Comment by kbengs** [comment] 2024-09-28 07:05
> fix 7: Don't use Windows 😉

:smile: 

Found out that adding: `locale.setlocale(locale.LC_ALL, '')` before setting `locale.setlocale(locale.LC_NUMERIC, 'C')` in exporter.py also does fix the issue, hinting we might do something wrong after all.. I'll continue investigating.

**Closed** 2024-10-08 13:13 UTC
Labels: need more info, Windows
