### ISSUE TITLE
Only some predefined pdf-properties can be set

### ISSUE THREAD

**Issue by klartext** [pdfarranger/pdfarranger#538] opened 2021-09-26 18:18 UTC
Describe the bug
----------------
Not all properties can be set for a pdf.
For example Author can't be set.
Only Title, Subject, Keywords, Producer, Creator, Creator Tool, Created, Modified are available in "Edit Properties" menu / pop-up.

To Reproduce
------------
Open a pdf.
Open menu, "Edit Properties"

Expected behavior
-----------------
More than the mentioned available properties can be edited.
For example "Add new property" for a new property (as long as it is conforming to pdf standard).
Than edit the value of that property.

System and Versions
-------------------
pdfarranger 1.7.1
Arch-linux package

**Comment by dreua** [comment] 2021-09-27 09:58
This is not a bug, we know and expect PDF Arranger to work that way. I personally never had the need to edit more metadata than accessible. Would you like explain your use case? I'm thinking, maybe we can simply add a few more often used fields, allowing arbitrary fields sounds a bit more complicate, also I'm worried about the user experience when people need to enter conforming property keys in a free text field.

**Comment by klartext** [comment] 2021-09-27 20:52
OK, feature wish might have been better than bug report. But when I opened the Issue, I was nugded to write a bug report ;-)

Use case: I needed to set pdf Metadata (Title, Author and some others) for a scanned pdf.
Looking around, my web search engine pointed me to a webpage, where pdfarranger was mentioned as one of some tools that are useful for this task.
The other tools mentioned there I didn't knew, so I thought: use the tool you already have installed and already have used to rearrange some pdf's. I was surprised but happy that editing Metadata also is seen as "arranging" a pdf.
My enthusiasm was then stopped, after I saw that the Author field was not available for editing.

I also hava a small script that reads out the pdf Metadata and renames my pdf files, so that the title from the Metadata is used as a new file name. So setting the Metadata first can be useful later for renaming the files (even though that is not always my use case).

**Comment by dreua** [comment] 2021-09-27 21:09
So if I understand correctly you are first and foremost missing the author field? That would be far more easy to add than allowing arbitrary fields. Would you / may I rename this issue accordingly?

**Comment by jeromerobert** [comment] 2021-09-29 07:40
> allowing arbitrary fields sounds a bit more complicate

+1000

@klartext Could you just provide the list of properties you are missing ?

**Comment by klartext** [comment] 2021-09-29 18:57
I need
```
Title
Subject
Author
Keywords
Creator
Producer
```

I looked again, what is available with pdfarranger, and it seems, only Author is missing.

**Comment by jeromerobert** [comment] 2021-09-30 13:26
[Evince](https://wiki.gnome.org/Apps/Evince) display `{http://purl.org/dc/elements/1.1/}creator` as `Author` and `{http://ns.adobe.com/xap/1.0/}CreatorTool` as `Creator`. PDF Arranger do the same.

Which meta data name do you expect in place of `{http://purl.org/dc/elements/1.1/}creator` for `Author` ? Could you provide a PDF with such meta data entry ?

**Comment by mara004** [comment] 2021-09-30 17:42
> Evince display {http://purl.org/dc/elements/1.1/}creator as Author and {http://ns.adobe.com/xap/1.0/}CreatorTool as Creator. PDF Arranger do the same.

@jeromerobert is right. I think @klartext's `Author` filed is just called `Creator` in PDF Arranger.

For some background, there are two different ways how metadata can be stored in PDFs: 
* the (deprecated) docinfo dictionary
* XMP metadata

pikepdf primarily works with XMP but automatically keeps docinfo consistent by mapping XMP keys to their docinfo equivalents where possible.
In docinfo, the displayed author is indicated by the `/Author` key; however in XMP syntax this is `dc:creator`. pikepdf automatically maps `dc:creator` to `/Author`.

**Comment by klartext** [comment] 2021-09-30 19:05
[metadata.pdf](https://github.com/pdfarranger/pdfarranger/files/7261907/metadata.pdf)

**Comment by jeromerobert** [comment] 2021-09-30 20:21
There is no issue. Author is "creator". Closing.
![image](https://user-images.githubusercontent.com/160365/135524685-12518f7a-c17d-4cd9-bea2-848a3c643175.png)

**Closed by jeromerobert** 2021-09-30 20:21 UTC
Labels: feature

**Comment by klartext** [comment] 2021-09-30 20:32
Metadata of metadata.pdf displayed with pdfinfo:

```
Title:          Title, of course.
Subject:        Topic of this document
Keywords:       Keyword1, Keyword2, ...
Author:         One or more authors.
Creator:        Which application, for example pdflatex.
Producer:       LaTeX with hyperref
CreationDate:   Thu Sep 30 21:02:24 2021 CEST
ModDate:        Thu Sep 30 21:02:24 2021 CEST
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          1
Encrypted:      no
Page size:      612 x 792 pts (letter)
Page rot:       0
File size:      10198 bytes
Optimized:      no
PDF version:    1.5
```

Copying metadata.pdf to test1.pdf, then editing "Creator" field, then using pdfinfo on test1.pdf gives:

```
Title:          Title, of course.
Subject:        Topic of this document
Keywords:       Keyword1, Keyword2, ...
Author:         Autors, changed with pdfarranger, using 'Creator' field
Creator:        Which application, for example pdflatex.
Producer:       LaTeX with hyperref
CreationDate:   Thu Sep 30 21:02:24 2021 CEST
ModDate:        Thu Sep 30 21:02:24 2021 CEST
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          1
Encrypted:      no
Page size:      612 x 792 pts (letter)
Page rot:       0
File size:      11153 bytes
Optimized:      no
PDF version:    1.3
```

So, if Author is present, editing Authjor with field "Creator"., and Creator is not changed by this editing.
That means, "Creator" in the menue is a misnomer.
And this then is a bug.

**Comment by mara004** [comment] 2021-10-01 11:09
> That means, "Creator" in the menue is a misnomer.
> And this then is a bug.

PDF Arranger just follows a different standard than what you are used to. pdfinfo uses the legacy docinfo names, whilst PDF Arranger follows the newer Dublin core convention. This is intentional and not an issue.

**Comment by mara004** [comment] 2021-10-01 11:11
> That means, "Creator" in the menue is a misnomer.
> And this then is a bug.

pdfarranger just follows a different standard than what you are used to. pdfinfo uses the legacy docinfo names, whilst pdfarranger follows the newer Dublin core convention. This is intentional and not an issue.
